require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecorridosController do

  # This should return the minimal set of attributes required to create a valid
  # Recorrido. As you add validations to Recorrido, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecorridosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all recorridos as @recorridos" do
      recorrido = Recorrido.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recorridos).should eq([recorrido])
    end
  end

  describe "GET show" do
    it "assigns the requested recorrido as @recorrido" do
      recorrido = Recorrido.create! valid_attributes
      get :show, {:id => recorrido.to_param}, valid_session
      assigns(:recorrido).should eq(recorrido)
    end
  end

  describe "GET new" do
    it "assigns a new recorrido as @recorrido" do
      get :new, {}, valid_session
      assigns(:recorrido).should be_a_new(Recorrido)
    end
  end

  describe "GET edit" do
    it "assigns the requested recorrido as @recorrido" do
      recorrido = Recorrido.create! valid_attributes
      get :edit, {:id => recorrido.to_param}, valid_session
      assigns(:recorrido).should eq(recorrido)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Recorrido" do
        expect {
          post :create, {:recorrido => valid_attributes}, valid_session
        }.to change(Recorrido, :count).by(1)
      end

      it "assigns a newly created recorrido as @recorrido" do
        post :create, {:recorrido => valid_attributes}, valid_session
        assigns(:recorrido).should be_a(Recorrido)
        assigns(:recorrido).should be_persisted
      end

      it "redirects to the created recorrido" do
        post :create, {:recorrido => valid_attributes}, valid_session
        response.should redirect_to(Recorrido.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recorrido as @recorrido" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recorrido.any_instance.stub(:save).and_return(false)
        post :create, {:recorrido => { "code" => "invalid value" }}, valid_session
        assigns(:recorrido).should be_a_new(Recorrido)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recorrido.any_instance.stub(:save).and_return(false)
        post :create, {:recorrido => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recorrido" do
        recorrido = Recorrido.create! valid_attributes
        # Assuming there are no other recorridos in the database, this
        # specifies that the Recorrido created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Recorrido.any_instance.should_receive(:update_attributes).with({ "code" => "MyString" })
        put :update, {:id => recorrido.to_param, :recorrido => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested recorrido as @recorrido" do
        recorrido = Recorrido.create! valid_attributes
        put :update, {:id => recorrido.to_param, :recorrido => valid_attributes}, valid_session
        assigns(:recorrido).should eq(recorrido)
      end

      it "redirects to the recorrido" do
        recorrido = Recorrido.create! valid_attributes
        put :update, {:id => recorrido.to_param, :recorrido => valid_attributes}, valid_session
        response.should redirect_to(recorrido)
      end
    end

    describe "with invalid params" do
      it "assigns the recorrido as @recorrido" do
        recorrido = Recorrido.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recorrido.any_instance.stub(:save).and_return(false)
        put :update, {:id => recorrido.to_param, :recorrido => { "code" => "invalid value" }}, valid_session
        assigns(:recorrido).should eq(recorrido)
      end

      it "re-renders the 'edit' template" do
        recorrido = Recorrido.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recorrido.any_instance.stub(:save).and_return(false)
        put :update, {:id => recorrido.to_param, :recorrido => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recorrido" do
      recorrido = Recorrido.create! valid_attributes
      expect {
        delete :destroy, {:id => recorrido.to_param}, valid_session
      }.to change(Recorrido, :count).by(-1)
    end

    it "redirects to the recorridos list" do
      recorrido = Recorrido.create! valid_attributes
      delete :destroy, {:id => recorrido.to_param}, valid_session
      response.should redirect_to(recorridos_url)
    end
  end

end
